sensor:
  - platform: homeassistant
    id: sensor_pv_power_1
    entity_id: sensor.pv_power
    on_value:
      - script.execute:
          id: update_pv_power_1
          x: !lambda return x;

  - platform: homeassistant
    id: sensor_pv_power_2
    entity_id: sensor.pv_power_2
    on_value:
      - script.execute:
          id: update_pv_power_2
          x: !lambda return x;

  - platform: combination
    type: sum
    id: sensor_pv_power_total
    sources:
      - source: sensor_pv_power_1
      - source: sensor_pv_power_2
    on_value:
      - script.execute:
          id: update_pv_power_total
          x: !lambda return x;

  - platform: homeassistant
    id: sensor_battery_power_1
    entity_id: sensor.battery_power
    on_value:
      then:
        - script.execute: adjust_offsets
        - script.execute:
            id: update_battery_power_1
            x: !lambda return x;

  - platform: homeassistant
    id: sensor_battery_power_2
    entity_id: sensor.white_bms_battery_power
    on_value:
      - script.execute: adjust_offsets
      - script.execute:
          id: update_battery_power_2
          x: !lambda return x;

  - platform: combination
    type: sum
    id: sensor_battery_power_total
    sources:
      - source: sensor_battery_power_1
      - source: sensor_battery_power_2
    on_value:
      - script.execute:
          id: update_battery_power_total
          x: !lambda return x;

  - platform: homeassistant
    id: sensor_battery_charge_1
    entity_id: sensor.battery_state_of_charge
    on_value:
      - script.execute:
          id: update_battery_charge_1
          x: !lambda return x;

  - platform: homeassistant
    id: sensor_battery_charge_2
    entity_id: sensor.battery_state_of_charge_2
    on_value:
      - script.execute:
          id: update_battery_charge_2
          x: !lambda return x;

  - platform: combination
    type: linear
    id: sensor_battery_charge_total
    sources:
      - source: sensor_battery_charge_1
        coeffecient: 0.46
      - source: sensor_battery_charge_2
        coeffecient: 0.53
    on_value:
      - script.execute:
          id: update_battery_charge_total
          x: !lambda return x;


  - platform: homeassistant
    id: inverter_1_battery_power
    entity_id: sensor.bms_battery_power
    on_value:
      script.execute: adjust_offsets
  - platform: homeassistant
    id: inverter_2_battery_power
    entity_id: sensor.white_bms_battery_power
    on_value:
      script.execute: adjust_offsets
  - platform: homeassistant
    id: inverter_2_battery_charge_state
    entity_id: sensor.white_bms_orient_charge

  - platform: homeassistant
    id: jakiper_charge_state
    entity_id: sensor.bms_jakiper_charge
  - platform: homeassistant
    id: byd_charge_state
    entity_id: sensor.bms_byd_charge

#  - platform: homeassistant
#    id: inverter_1_battery_charge_state
#    entity_id: sensor.battery_state_of_charge

  - platform: combination
    type: mean
    id: inverter_1_battery_charge_state
    sources:
      - source: byd_charge_state
      - source: jakiper_charge_state


